### ISSUE TITLE
whitelist kundencenter.telekom.de

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List#2]
kundencenter.telekom.de is in the list and I have to sign up on their website to tell them that they should qualify their sources...

**Comment by funilrys** [comment]
@Somebodyisnobody reported to upstream ?

**Comment by Somebodyisnobody** [comment]
I would have to sign up on their website, so I haven't reported it.

**Comment by funilrys** [comment]
Upstream == https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List/blob/ac3aa94d28a66958adcb20b09b39dd1c9702cd92/info.json#L31 @Somebodyisnobody

**Comment by Somebodyisnobody** [comment]
And where I can report the wrong link?
